<project xmlns="http://maven.apache.org/POM/4.0.0"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
	<modelVersion>4.0.0</modelVersion>
	<groupId>com</groupId>
	<artifactId>pizza-jsf</artifactId>
	<version>0.0.1-SNAPSHOT</version>
	<packaging>war</packaging>
	<name>Pizza-jsf</name>
	<description>Spring boot - Primefaces</description>

	<parent>
		<groupId>org.joinfaces</groupId>
		<artifactId>joinfaces-parent</artifactId>
		<version>3.2.1</version>
		<relativePath /> <!-- lookup parent from repository -->
	</parent>

	<properties>
		<project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
		<java.version>10</java.version>
	</properties>

	<dependencies>
		<!-- joinfaces -->
		<dependency>
			<groupId>org.joinfaces</groupId>
			<artifactId>primefaces-spring-boot-starter</artifactId>
		</dependency>

		<!-- CGLIB is required to process @Configuration classes -->
		<dependency>
			<groupId>cglib</groupId>
			<artifactId>cglib</artifactId>
			<version>2.2.2</version>
		</dependency>
		<!-- Servlet API, JSTL -->
		<dependency>
			<groupId>javax.servlet</groupId>
			<artifactId>javax.servlet-api</artifactId>
			<scope>provided</scope>
		</dependency>
		<dependency>
			<groupId>jstl</groupId>
			<artifactId>jstl</artifactId>
			<version>1.2</version>
		</dependency>

	</dependencies>

	<build>
		<plugins>
			<!-- spring-boot-maven-plugin -->
			<plugin>
				<groupId>org.springframework.boot</groupId>
				<artifactId>spring-boot-maven-plugin</artifactId>
				<executions>
					<execution>
						<goals>
							<goal>build-info</goal>
						</goals>
						<configuration>
							<configuration>
								<additionalProperties>
									<encoding.source>${project.build.sourceEncoding}</encoding.source>
									<encoding.reporting>${project.build.sourceEncoding}</encoding.reporting>
									<java.source>${java.version}</java.source>
									<java.target>${java.version}</java.target>
								</additionalProperties>
							</configuration>
						</configuration>
					</execution>
				</executions>
			</plugin>
		</plugins>
	</build>
</project>